"""
services/history.py
-------------------
Manages persistent chat history using SQLite.

Why SQLite here?
  ChromaDB is a vector store — great for semantic search, not for ordered logs.
  SQLite is purpose-built for structured, ordered, persistent data with zero
  extra infrastructure (just a file on disk).

Schema:
  messages(id, session_id, role, content, created_at)

  - session_id : generated by the frontend per conversation, sent with every request
  - role       : "user" or "assistant"
  - content    : raw message text
  - created_at : UTC timestamp for ordering and future display

Usage:
  history = ChatHistory()               # call once, import the instance
  history.add("sess-123", "user", "What is ML?")
  history.add("sess-123", "assistant", "ML is...")
  turns = history.get_recent("sess-123", limit=10)
  # → [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}]
"""

import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path

DB_PATH = Path("data/chat_history.db")


class ChatHistory:
    """
    Thread-safe SQLite-backed chat history store.

    SQLite connections cannot be shared across threads, so we use
    threading.local() to give each thread its own connection.
    The database file and table are created automatically on first use.
    """

    def __init__(self, db_path: Path = DB_PATH):
        self._db_path = db_path
        self._local = threading.local()
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        # Initialise the schema on startup using a temporary connection
        self._init_schema()

    # ------------------------------------------------------------------
    # Connection management
    # ------------------------------------------------------------------

    def _conn(self) -> sqlite3.Connection:
        """
        Return the connection for the current thread, creating it if needed.
        Each thread gets its own connection — SQLite requires this.
        """
        if not hasattr(self._local, "conn") or self._local.conn is None:
            self._local.conn = sqlite3.connect(str(self._db_path), check_same_thread=False)
            self._local.conn.row_factory = sqlite3.Row   # rows behave like dicts
        return self._local.conn

    def _init_schema(self) -> None:
        """Create the messages table if it doesn't already exist."""
        conn = self._conn()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS messages (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id  TEXT    NOT NULL,
                role        TEXT    NOT NULL CHECK(role IN ('user', 'assistant')),
                content     TEXT    NOT NULL,
                created_at  TEXT    NOT NULL
            )
        """)
        # Index on session_id so per-session queries are fast even at scale
        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_session_id ON messages(session_id)
        """)
        conn.commit()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add(self, session_id: str, role: str, content: str) -> None:
        """Append a single message to a session's history."""
        conn = self._conn()
        conn.execute(
            "INSERT INTO messages (session_id, role, content, created_at) VALUES (?, ?, ?, ?)",
            (session_id, role, content, datetime.now(timezone.utc).isoformat()),
        )
        conn.commit()

    def get_recent(self, session_id: str, limit: int = 10) -> list[dict]:
        """
        Return the last `limit` messages for a session, oldest first.

        We fetch the most recent N using ORDER BY id DESC LIMIT N, then
        reverse so the LLM sees them in chronological order.
        """
        conn = self._conn()
        rows = conn.execute(
            """
            SELECT role, content FROM messages
            WHERE session_id = ?
            ORDER BY id DESC
            LIMIT ?
            """,
            (session_id, limit),
        ).fetchall()
        # Reverse to get chronological order (oldest → newest)
        return [{"role": r["role"], "content": r["content"]} for r in reversed(rows)]

    def get_all(self, session_id: str) -> list[dict]:
        """
        Return every message for a session with timestamps.
        Used by GET /history/{session_id} for the frontend conversation view.
        """
        conn = self._conn()
        rows = conn.execute(
            """
            SELECT role, content, created_at FROM messages
            WHERE session_id = ?
            ORDER BY id ASC
            """,
            (session_id,),
        ).fetchall()
        return [dict(r) for r in rows]

    def get_sessions(self) -> list[dict]:
        """
        Return a summary of all sessions: session_id, message count,
        and the timestamp of the first message.
        Used by GET /history to list past conversations.
        """
        conn = self._conn()
        rows = conn.execute(
            """
            SELECT
                session_id,
                COUNT(*) as message_count,
                MIN(created_at) as started_at
            FROM messages
            GROUP BY session_id
            ORDER BY started_at DESC
            """
        ).fetchall()
        return [dict(r) for r in rows]

    def delete_session(self, session_id: str) -> None:
        """Delete all messages for a session (e.g. user clears a conversation)."""
        conn = self._conn()
        conn.execute("DELETE FROM messages WHERE session_id = ?", (session_id,))
        conn.commit()


# Single shared instance imported by routes and rag.py
chat_history = ChatHistory()